imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
          default:
            mappings:

              SysCrunchBaseInitialBundle: ~

              SysCrunchStoreBundle: ~

              gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false

              gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false

              gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false

              gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

stof_doctrine_extensions:
    default_locale: en_US
    translation_fallback: true
    orm:
        default:
          tree:           true
          timestampable:  true
          loggable:       true
          translatable:   true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_security_extra:
  secure_all_services: false
  expressions: true

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true

sensio_framework_extra:
  router: { annotations: true }
  request: { converters: true }
  view: { annotations: false }
  cache: { annotations: true }


jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

fos_user:
    db_driver: orm
    firewall_name: wsse_secured #fos_secured
    user_class: SysCrunch\Base\InitialBundle\Entity\User

fos_rest:
  allowed_methods_listener: true
  param_fetcher_listener: true
  view:
    view_response_listener: true
    formats:
      xml:  true
      json: true
    templating_formats:
      html: false
    mime_types:
      json: "application/json"
      xml: "application/xml"
  format_listener: 
    default_priorities:
      - json
      - xml
      - html
    fallback_format: json
  body_listener: false
  exception:
    codes:
      'Pagerfanta\Exception\NotValidCurrentPageException': 404
      'Pagerfanta\Exception\NotValidMaxPerPageException': 404

mopa_wsse_authentication:
  provider_class: Mopa\Bundle\WSSEAuthenticationBundle\Security\Authentication\Provider\WsseAuthenticationProvider
  listener_class: Mopa\Bundle\WSSEAuthenticationBundle\Security\Firewall\WsseListener
  factory_class: Mopa\Bundle\WSSEAuthenticationBundle\Security\Factory\WsseFactory

nelmio_api_doc: ~

jms_di_extra:
  locations:
    bundles: [ SysCrunchStoreBundle ]

fsc_hateoas:
  pagerfanta:
    parameters_name:
      page: pagination[page]
      limit: pagination[limit]

#hwi_oauth:
#    connect:
#      account_connector: my_user_provider
#    firewall_name: secured_area
#    fosub:
#      username_iterations: 30
#      properties:
#          # these properties will be used/redefined later in the custom FOSUBUserProvider service.
#          facebook: facebook_id
#    resource_owners:
#      facebook:
#        type:               facebook
#        client_id:          615692801788186
#        client_secret:      823d210ae4ea00eeb149d894a74cc51a
#        scope:               "email"
#        options:
#          display:          popup
#      twitter:
#        type:                twitter
#        client_id:           W1eEMcSn07sUSK0vK8eNRw
#        client_secret:       w61OtRerQ4Xply5OOlZTvu85bpz2A5Ys9QYs1JlO4
#services:
#  hwi_oauth.user.provider.entity:
#    class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider